// Harleigh Abel 
// CS50 pset2 Jan 2016
// caesar.c
// This program encrypts user's plaintext message using 
// caesar cipher with a key generated by the user at the command prompt

#include <cs50.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>

int main(int argc, char* argv[])
{


// Check to ensure a single argument (the key) 
// has been input by the user at command prompt upon initializing the program
// otherwise print error message and create a return value of 1.

    if (argc != 2)
        {
        printf("Invalid input! Please enter a single postive integer");
        printf(" to create a valid key!\n");
        return 1;
        }
        
        
    else
        {
        // Store key input at command prompt
        int key = (int) char* argv[2];
        
        // Prompt user for plain text message 
        printf("Please type your plaintext message to be encoded!");
        printf("%d\n", key);
        
        // implement and store plaintext variable address
        char* plaintext = GetString();
        
        // encode plaintext with CaesarEncode function
        char* secret_message = CaesarEncode(plaintext);
        
        // print encoded message to the screen
        printf("%s\n", secret_message)
        
        }
        
    CaesarEncode()
        {}
        
        return 0;
}
